name: Run Renovate

on:
  workflow_dispatch:
    inputs:
      log-level:
        description: "Log level"
        type: choice
        default: info
        options:
          - info
          - debug
          - trace
      repo-cache:
        description: "Reset or disable the cache?"
        type: choice
        default: enabled
        options:
          - enabled
          - disabled
          - reset
  schedule:
    - cron: "0,30 * * * *"
  pull_request:
    paths: &paths
      - ".github/workflows/renovate.yaml"
      - ".github/renovate-config.ts"
      - "default.json"
      - "preset.json5"
  push:
    branches:
      - main
    paths: *paths

env:
  cache_dir: /tmp/renovate/cache/renovate/repository
  cache_key: renovate-cache
  RENOVATE_VERSION: 44.65.5@sha256:4e10f76a79f1c597f427f83c788a9f5b14a6295784c4cb68307b89b0a954abce # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  renovate:
    name: Renovate
    environment:
      name: renovate
      deployment: false
    runs-on: ubuntu-26.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0  # zizmor: ignore[github-app]
        with:
          client-id: ${{ secrets.RENOVATE_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            .github
            digital-earth-sweden-community
            umbrella

      - name: Restore renovate cache
        id: cache-restore
        if: github.event.inputs.repo-cache != 'disabled' && github.event.inputs.repo-cache != 'reset'
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.cache_dir }}
          key: ${{ env.cache_key }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ env.cache_key }}-

      - name: Fix restored cache ownership
        if: steps.cache-restore.outputs.cache-matched-key != ''
        run: |
          sudo chown -R 12021:0 /tmp/renovate/
          ls -R $cache_dir

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@5402b206248e5a8c8427a15102702eb9c1793efc # v46.2.4
        with:
          configurationFile: "config.js"
          docker-volumes: |
            ${{ github.workspace }}/.github/renovate-config.ts:/github-action/.github/renovate-config.ts
          renovate-version: ${{ env.RENOVATE_VERSION }}
          token: ${{ steps.get_token.outputs.token }}
        env:
          # Job configuration.
          LOG_LEVEL: ${{ inputs.log-level || 'info' }}
          RENOVATE_PLATFORM_COMMIT: "enabled"
          RENOVATE_REPOSITORY_CACHE: ${{ github.event.inputs.repo-cache || 'enabled' }}
          # Credentials
          RENOVATE_HARBOR_DIGITALEARTH_SE_USER: ${{ secrets.RENOVATE_HARBOR_DIGITALEARTH_SE_USER }}
          RENOVATE_HARBOR_DIGITALEARTH_SE_PASSWORD: ${{ secrets.RENOVATE_HARBOR_DIGITALEARTH_SE_PASSWORD }}

      - name: Save renovate cache
        if: github.event.inputs.repo-cache != 'disabled' && steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.cache_dir }}
          key: ${{ env.cache_key }}-${{ github.run_id }}-${{ github.run_attempt }}
